# Accordion component
accordion:
  - src/oseille/4-components/_collapse.scss
# Styling base elements
base element:
  - src/oseille/3-elements/base/*
# Backgrounds and borders component
border:
  - src/oseille/2-settings/_borders.scss
  - src/oseille/4-components/_border.scss
# The box model
box model:
  - src/oseille/2-settings/_box-model.scss
# Card component
card:
  - src/oseille/4-components/_card.scss
# Color styling
color:
  - src/oseille/2-settings/_colors.scss
# Improvements or additions to documentation
documentation:
  - docs/*
# Menu drawer component
drawer:
  - src/oseille/4-components/_drawer.scss
# Styling images, media, and form elements
form:
  - src/oseille/3-elements/base/_form.scss
  - src/oseille/3-elements/base/_multimedia.scss
# Grid system and container
grid system:
  - src/oseille/4-components/_grid.scss
# Modal & dialog component
modal:
  - src/oseille/4-components/_modal.scss
# Progress and spinner component
progress:
  - src/oseille/4-components/_progress.scss
# Responsive concern
responsiveness:
  - src/oseille/2-settings/_responsive.scss
# Styling tables
table:
  - src/oseille/3-elements/base/_table.scss
# Typo, semantic and text content styling
text:
  - src/oseille/3-elements/base/_text.scss
  - src/oseille/2-settings/_fonts.scss
  - src/oseille/4-components/_legibility.scss
  - src/oseille/3-elements/layout/_heading.scss
# Toast component
toast:
  - src/oseille/4-components/_toast.scss
# Tooltip component
tooltips:
 - src/oseille/4-components/_tooltip.scss
