name: Build

# on: [push, pull_request]
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [14.x,16.x]


    steps:
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies & Build
        run: |
          npm install
          npm run build
